import { GearType } from './data';
import { getAllGearTypes } from './testUtils';

test('getAllGearTypes contains all gear types', () => {
  const all: Record<GearType, boolean> = {
    [GearType.cap]: false,
    [GearType.faceAccessory]: false,
    [GearType.eyeAccessory]: false,
    [GearType.earrings]: false,
    [GearType.coat]: false,
    [GearType.longcoat]: false,
    [GearType.pants]: false,
    [GearType.shoes]: false,
    [GearType.glove]: false,
    [GearType.cape]: false,
    [GearType.ring]: false,
    [GearType.pendant]: false,
    [GearType.belt]: false,
    [GearType.medal]: false,
    [GearType.shoulder]: false,
    [GearType.pocket]: false,
    [GearType.badge]: false,
    [GearType.android]: false,
    [GearType.machineHeart]: false,
    [GearType.shield]: false,
    [GearType.emblem]: false,
    [GearType.powerSource]: false,
    [GearType.shiningRod]: false,
    [GearType.tuner]: false,
    [GearType.breathShooter]: false,
    [GearType.longSword2]: false,
    [GearType.soulShooter]: false,
    [GearType.desperado]: false,
    [GearType.energySword]: false,
    [GearType.espLimiter]: false,
    [GearType.chain]: false,
    [GearType.magicGauntlet]: false,
    [GearType.ritualFan]: false,
    [GearType.ohSword]: false,
    [GearType.ohAxe]: false,
    [GearType.ohBlunt]: false,
    [GearType.dagger]: false,
    [GearType.katara]: false,
    [GearType.cane]: false,
    [GearType.wand]: false,
    [GearType.staff]: false,
    [GearType.thSword]: false,
    [GearType.chakram]: false,
    [GearType.thAxe]: false,
    [GearType.thBlunt]: false,
    [GearType.spear]: false,
    [GearType.polearm]: false,
    [GearType.bow]: false,
    [GearType.crossbow]: false,
    [GearType.claw]: false,
    [GearType.knuckle]: false,
    [GearType.gun]: false,
    [GearType.shovel]: false,
    [GearType.pickaxe]: false,
    [GearType.dualBowguns]: false,
    [GearType.handCannon]: false,
    [GearType.heavySword]: false,
    [GearType.longSword]: false,
    [GearType.gauntletRevolver]: false,
    [GearType.ancientBow]: false,
    [GearType.soulShield]: false,
    [GearType.demonShield]: false,
    [GearType.magicArrow]: false,
    [GearType.card]: false,
    [GearType.medallion]: false,
    [GearType.rosary]: false,
    [GearType.ironChain]: false,
    [GearType.magicBook1]: false,
    [GearType.magicBook2]: false,
    [GearType.magicBook3]: false,
    [GearType.arrowFletching]: false,
    [GearType.bowThimble]: false,
    [GearType.daggerScabbard]: false,
    [GearType.charm]: false,
    [GearType.orb]: false,
    [GearType.dragonEssence]: false,
    [GearType.soulRing]: false,
    [GearType.magnum]: false,
    [GearType.wristBand]: false,
    [GearType.farSight]: false,
    [GearType.powderKeg]: false,
    [GearType.mass]: false,
    [GearType.document]: false,
    [GearType.magicMarble]: false,
    [GearType.arrowhead]: false,
    [GearType.jewel]: false,
    [GearType.powderKeg2]: false,
    [GearType.controller]: false,
    [GearType.foxMarble]: false,
    [GearType.chessPiece]: false,
    [GearType.transmitter]: false,
    [GearType.charge]: false,
    [GearType.magicWing]: false,
    [GearType.pathOfAbyss]: false,
    [GearType.relic]: false,
    [GearType.fanTassel]: false,
    [GearType.bracelet]: false,
    [GearType.weaponBelt]: false,
    [GearType.ornament]: false,
    [GearType.hexSeeker]: false,
    [GearType.sacredJewel]: false,
    [GearType.petEquip]: false,
    [GearType.machineEngine]: false,
    [GearType.machineArms]: false,
    [GearType.machineLegs]: false,
    [GearType.machineBody]: false,
    [GearType.machineTransistors]: false,
    [GearType.dragonMask]: false,
    [GearType.dragonPendant]: false,
    [GearType.dragonWings]: false,
    [GearType.dragonTail]: false,
  };
  const expected = Object.fromEntries(
    Object.entries(all).map(([key]) => [key, true]),
  );

  for (const gearType of getAllGearTypes()) {
    all[gearType] = true;
  }

  expect(all).toEqual(expected);
});
