export const enum ErrorCode {
  /** 미사용 */
  DEFAULT = 0,

  // 도메인_작업_실패원인.
  AddOption_Apply_NotSupported,
  AddOption_Apply_MaxCountOf4Reached,
  AddOption_Reset_NotSupported,
  AddOption_Calculate_AttackPowerRequiresWeaponOrReqLevelAtLeast60,
  AddOption_Calculate_MagicPowerRequiresWeaponOrReqLevelAtLeast60,
  AddOption_Calculate_UnknownLongSwordAttackPower,
  AddOption_Calculate_SpeedRequiresNonWeapon,
  AddOption_Calculate_JumpRequiresNonWeapon,
  AddOption_Calculate_DamageRequiresWeapon,
  AddOption_Calculate_BossDamageRequiresWeapon,
  AddOption_Calculate_BossDamageReqLevelBelow90,
  AddOption_Calculate_AllStatRequiresWeaponOrReqLevelAtLeast70,
  AddOption_Calculate_ReqLevelDecreaseRequiresPositiveReqLevel,

  Upgrade_ApplyScroll_NotSupported,
  Upgrade_ApplyScroll_NoRemainingUpgradeCount,
  Upgrade_FailScroll_NotSupported,
  Upgrade_FailScroll_NoRemainingUpgradeCount,
  Upgrade_ResileScroll_NotSupported,
  Upgrade_ResileScroll_NoResilienceCount,
  Upgrade_Reset_NotSupported,
  SpellTrace_CreateScroll_UnsupportedGearType,
  SpellTrace_CreateScroll_UnsupportedSpellTraceType,
  SpellTrace_CreateScroll_UnsupportedSpellTraceRate,
  SpellTrace_CreateScroll_UnsupportedTypeRateCombination,

  Starforce_Apply_NotSupported,
  Starforce_Apply_Fixed,
  Starforce_Apply_MaxStarReached,
  Starforce_Apply_AbsoluteMaxStarReached,
  Starforce_Apply_SuperiorMaxStarReached,
  Starforce_Calculate_UnsupportedReqLevel,
  Starforce_Reset_NotSupported,
  Starforce_Reset_Fixed,
  Starforce_Recalculate_NotSupported,
  Starforce_Recalculate_StarScrollApplied,
  StarScroll_Apply_NotSupported,
  StarScroll_Apply_Fixed,
  StarScroll_Apply_SuperiorNotSupported,
  StarScroll_Apply_ReqLevelAbove150,
  StarScroll_Apply_MaxStarReached,
  StarScroll_Apply_AbsoluteMaxStarReached,

  Potential_Set_NotSupported,
  Potential_Set_Fixed,
  Potential_Set_NormalGradeNotAllowed,
  Potential_Set_OptionCountOutOfRange,
  Potential_Reset_NotSupported,
  AdditionalPotential_Set_NotSupported,
  AdditionalPotential_Set_Fixed,
  AdditionalPotential_Set_NormalGradeNotAllowed,
  AdditionalPotential_Set_OptionCountOutOfRange,
  AdditionalPotential_Reset_NotSupported,

  SoulWeapon_Enchant_NotWeapon,
  SoulWeapon_Enchant_AlreadyEnchanted,
  SoulWeapon_Equip_NotEnchanted,
  SoulWeapon_Equip_AmplifiedSlotRequiresAmplifiableSoul,
  SoulWeapon_Amplify_ReqLevelBelow200,
  SoulWeapon_Amplify_NotEnchanted,
  SoulWeapon_Amplify_NoSoulEquipped,
  SoulWeapon_Amplify_EquippedSoulNotAmplifiable,
  SoulWeapon_Amplify_MaxLevelReached,
  SoulWeapon_SetPotential_NotEnchanted,
  SoulWeapon_SetPotential_NotAmplified,
  SoulWeapon_SetPotential_NoSoulEquipped,
  SoulWeapon_SetPotential_EquippedSoulNotAmplifiable,
  SoulWeapon_SetPotential_NormalGradeNotAllowed,
  SoulWeapon_SetPotential_OptionCountNotThree,

  Exceptional_Apply_NotSupported,
  Exceptional_Apply_NoRemainingUpgradeCount,
  Exceptional_Reset_NotSupported,

  Shape_Set_ChangeNotAllowed,

  Gear_Construct_UnsupportedDataVersion,
  Gear_Migrate_InvalidGearData,
  Gear_Migrate_DataVersionTooNew,
  Gear_Migrate_UnknownDataVersion,
}
