import { GearData, GearType } from '../data';

export const resources = {
  '': {
    meta: {
      id: 1000000,
      version: 1,
    },
    name: '테스트용 장비',
    icon: '1000000',
    type: 100,
    req: {},
    attributes: {},
  },
  '핑크빈 모자': {
    meta: {
      id: 1003450,
      version: 1,
    },
    name: '핑크빈 모자',
    icon: '1002971',
    type: 100,
    req: {
      level: 13,
    },
    attributes: {
      canStarforce: 1,
      canScroll: 1,
      canAddOption: 1,
      canPotential: 1,
      canAdditionalPotential: 1,
    },
    baseOption: {
      str: 1,
      dex: 1,
      int: 1,
      luk: 1,
    },
    scrollUpgradeableCount: 11,
  },
  '리버스 휀넬': {
    meta: {
      id: 1002790,
      version: 1,
    },
    name: '리버스 휀넬',
    icon: '1002776',
    type: 100,
    req: {
      level: 120,
      job: 1,
    },
    attributes: {
      trade: 2,
      canStarforce: 1,
      canScroll: 1,
      canAddOption: 1,
      canPotential: 1,
      canAdditionalPotential: 1,
    },
    baseOption: {
      str: 6,
      armor: 120,
    },
    scrollUpgradeableCount: 8,
  },
  '노가다 목장갑': {
    meta: {
      id: 1082002,
      version: 1,
    },
    name: '노가다 목장갑',
    icon: '1082002',
    type: 108,
    req: {
      level: 10,
    },
    attributes: {
      canStarforce: 1,
      canScroll: 1,
      canAddOption: 1,
      canPotential: 1,
      canAdditionalPotential: 1,
    },
    baseOption: {
      armor: 2,
    },
    scrollUpgradeableCount: 6,
  },
  '튼튼한 기계 장갑': {
    meta: {
      id: 1082283,
      version: 1,
    },
    name: '튼튼한 기계 장갑',
    icon: '1082222',
    type: 108,
    req: {
      level: 90,
    },
    attributes: {
      canStarforce: 1,
      canScroll: 1,
      canAddOption: 1,
      canPotential: 1,
      canAdditionalPotential: 1,
    },
    baseOption: {
      armor: 30,
    },
    scrollUpgradeableCount: 6,
  },
  '블랙 가리나 글로브': {
    meta: {
      id: 1082167,
      version: 1,
    },
    name: '블랙 가리나 글로브',
    icon: '1082167',
    type: 108,
    req: {
      level: 110,
      job: 8,
    },
    attributes: {
      canStarforce: 1,
      canScroll: 1,
      canAddOption: 1,
      canPotential: 1,
      canAdditionalPotential: 1,
    },
    baseOption: {
      dex: 5,
      luk: 6,
      armor: 43,
    },
    scrollUpgradeableCount: 6,
  },
  '펜살리르 스키퍼부츠': {
    meta: {
      id: 1072971,
      version: 1,
    },
    name: '펜살리르 스키퍼부츠',
    icon: '1072967',
    type: 107,
    req: {
      level: 140,
      job: 16,
    },
    attributes: {
      canStarforce: 1,
      canScroll: 1,
      canAddOption: 1,
      canPotential: 1,
      canAdditionalPotential: 1,
    },
    baseOption: {
      str: 10,
      dex: 10,
      attackPower: 1,
      armor: 80,
      speed: 5,
    },
    scrollUpgradeableCount: 7,
  },
  '앱솔랩스 시프슈즈': {
    meta: {
      id: 1073034,
      version: 1,
    },
    name: '앱솔랩스 시프슈즈',
    icon: '1073030',
    type: 107,
    req: {
      level: 160,
      job: 8,
    },
    attributes: {
      trade: 2,
      cuttable: 2,
      bossReward: true,
      incline: {
        charm: 100,
      },
      canStarforce: 1,
      canScroll: 1,
      canAddOption: 1,
      canPotential: 1,
      canAdditionalPotential: 1,
    },
    baseOption: {
      dex: 20,
      luk: 20,
      attackPower: 5,
      armor: 150,
      speed: 10,
      jump: 7,
    },
    scrollUpgradeableCount: 8,
  },
  '노바 히아데스 클록': {
    meta: {
      id: 1102476,
      version: 1,
    },
    name: '노바 히아데스 클록',
    icon: '1102476',
    type: 110,
    req: {
      level: 110,
      job: 1,
    },
    attributes: {
      trade: 1,
      cuttable: 2,
      superior: true,
      canStarforce: 1,
      canScroll: 1,
      canAddOption: 1,
      canPotential: 1,
      canAdditionalPotential: 1,
    },
    baseOption: {
      str: 30,
      dex: 30,
      int: 30,
      luk: 30,
      attackPower: 17,
      magicPower: 17,
      armor: 70,
    },
    scrollUpgradeableCount: 2,
  },
  '타일런트 케이론 클록': {
    meta: {
      id: 1102483,
      version: 1,
    },
    name: '타일런트 케이론 클록',
    icon: '1102481',
    type: 110,
    req: {
      level: 150,
      job: 4,
    },
    attributes: {
      trade: 1,
      cuttable: 2,
      bossReward: true,
      superior: true,
      canStarforce: 1,
      canScroll: 1,
      canAddOption: 1,
      canPotential: 1,
      canAdditionalPotential: 1,
    },
    baseOption: {
      str: 50,
      dex: 50,
      int: 50,
      luk: 50,
      attackPower: 30,
      magicPower: 30,
      armor: 150,
    },
    scrollUpgradeableCount: 3,
  },
  '에테르넬 나이트케이프': {
    meta: {
      id: 1103433,
      version: 1,
    },
    name: '에테르넬 나이트케이프',
    icon: '1103433',
    type: 110,
    req: {
      level: 250,
      job: 1,
    },
    attributes: {
      trade: 2,
      cuttable: 2,
      bossReward: true,
      incline: {
        charm: 100,
      },
      canStarforce: 1,
      canScroll: 1,
      canAddOption: 1,
      canPotential: 1,
      canAdditionalPotential: 1,
    },
    baseOption: {
      str: 50,
      dex: 50,
      int: 50,
      luk: 50,
      attackPower: 9,
      magicPower: 9,
      armor: 600,
    },
    scrollUpgradeableCount: 8,
  },
  '스칼렛 숄더': {
    meta: {
      id: 1152155,
      version: 1,
    },
    name: '스칼렛 숄더',
    icon: '1152155',
    type: 115,
    req: {
      level: 135,
    },
    attributes: {
      trade: 2,
      cuttable: 2,
      lucky: true,
      bossReward: true,
      canStarforce: 1,
      canScroll: 1,
      canPotential: 1,
      canAdditionalPotential: 1,
    },
    baseOption: {
      str: 12,
      dex: 12,
      int: 12,
      luk: 12,
      maxHp: 400,
      attackPower: 7,
      magicPower: 7,
      armor: 125,
    },
    scrollUpgradeableCount: 2,
  },
  '카오스 혼테일의 목걸이': {
    meta: {
      id: 1122076,
      version: 1,
    },
    name: '카오스 혼테일의 목걸이',
    icon: '1122076',
    type: 112,
    req: {
      level: 120,
    },
    attributes: {
      trade: 1,
      onlyEquip: true,
      cuttable: 2,
      incline: {
        charm: 80,
      },
      canStarforce: 1,
      canScroll: 1,
      canAddOption: 1,
      canPotential: 1,
      canAdditionalPotential: 1,
    },
    baseOption: {
      str: 10,
      dex: 10,
      int: 10,
      luk: 10,
      maxHpRate: 10,
      maxMpRate: 10,
      attackPower: 2,
      magicPower: 2,
      armor: 140,
    },
    scrollUpgradeableCount: 3,
  },
  '데아 시두스 이어링': {
    meta: {
      id: 1032241,
      version: 1,
    },
    name: '데아 시두스 이어링',
    icon: '1032241',
    type: 103,
    req: {
      level: 130,
    },
    attributes: {
      trade: 2,
      cuttable: 2,
      bossReward: true,
      canStarforce: 1,
      canScroll: 1,
      canAddOption: 1,
      canPotential: 1,
      canAdditionalPotential: 1,
    },
    baseOption: {
      str: 5,
      dex: 5,
      int: 5,
      luk: 5,
      attackPower: 2,
      magicPower: 2,
      armor: 50,
    },
    scrollUpgradeableCount: 7,
  },
  '몽환의 벨트': {
    meta: {
      id: 1132308,
      version: 1,
    },
    name: '몽환의 벨트',
    icon: '1132308',
    type: 113,
    req: {
      level: 200,
    },
    attributes: {
      trade: 2,
      cuttable: 2,
      cuttableCount: 5,
      totalCuttableCount: 5,
      bossReward: true,
      canStarforce: 1,
      canScroll: 1,
      canAddOption: 1,
      canPotential: 1,
      canAdditionalPotential: 1,
    },
    baseOption: {
      str: 50,
      dex: 50,
      int: 50,
      luk: 50,
      maxHp: 150,
      maxMp: 150,
      attackPower: 6,
      magicPower: 6,
      armor: 150,
    },
    scrollUpgradeableCount: 4,
    exceptionalUpgradeableCount: 1,
  },
  '스칼렛 링': {
    meta: {
      id: 1113070,
      version: 1,
    },
    name: '스칼렛 링',
    icon: '1113070',
    type: 111,
    req: {
      level: 135,
    },
    attributes: {
      trade: 2,
      onlyEquip: true,
      cuttable: 2,
      lucky: true,
      bossReward: true,
      canStarforce: 1,
      canScroll: 1,
      canPotential: 1,
      canAdditionalPotential: 1,
    },
    baseOption: {
      str: 4,
      dex: 4,
      int: 4,
      luk: 4,
      maxHp: 150,
      maxMp: 150,
      attackPower: 1,
      magicPower: 1,
      armor: 100,
    },
    scrollUpgradeableCount: 2,
  },
  '근원의 속삭임': {
    meta: {
      id: 1113341,
      version: 1,
    },
    name: '근원의 속삭임',
    icon: '1113341',
    type: 111,
    req: {
      level: 250,
    },
    attributes: {
      trade: 2,
      onlyEquip: true,
      cuttable: 2,
      cuttableCount: 5,
      totalCuttableCount: 5,
      bossReward: true,
      canStarforce: 1,
      canScroll: 1,
      canPotential: 1,
      canAdditionalPotential: 1,
    },
    baseOption: {
      str: 10,
      dex: 10,
      int: 10,
      luk: 10,
      maxHp: 500,
      maxMp: 500,
      attackPower: 5,
      magicPower: 5,
    },
    scrollUpgradeableCount: 4,
  },
  '데이브레이크 펜던트': {
    meta: {
      id: 1122443,
      version: 1,
    },
    name: '데이브레이크 펜던트',
    icon: '1122443',
    type: 112,
    req: {
      level: 140,
    },
    attributes: {
      trade: 2,
      onlyEquip: true,
      cuttable: 2,
      bossReward: true,
      incline: {
        charm: 150,
      },
      canStarforce: 1,
      canScroll: 1,
      canAddOption: 1,
      canPotential: 1,
      canAdditionalPotential: 1,
    },
    baseOption: {
      str: 8,
      dex: 8,
      int: 8,
      luk: 8,
      maxHpRate: 5,
      attackPower: 2,
      magicPower: 2,
      armor: 100,
    },
    scrollUpgradeableCount: 6,
  },
  '리튬 하트': {
    meta: {
      id: 1672007,
      version: 1,
    },
    name: '리튬 하트',
    icon: '1672007',
    type: 167,
    req: {
      level: 30,
    },
    attributes: {
      trade: 2,
      canStarforce: 1,
      canScroll: 1,
      canPotential: 1,
      canAdditionalPotential: 1,
    },
    baseOption: {
      str: 3,
      dex: 3,
      int: 3,
      luk: 3,
      maxHp: 50,
    },
    scrollUpgradeableCount: 8,
  },
  '페어리 하트': {
    meta: {
      id: 1672073,
      version: 1,
    },
    name: '페어리 하트',
    icon: '1672073',
    type: 167,
    req: {
      level: 100,
    },
    attributes: {
      trade: 2,
      canStarforce: 1,
      canScroll: 1,
      canPotential: 1,
      canAdditionalPotential: 1,
    },
    baseOption: {
      maxHp: 100,
    },
    scrollUpgradeableCount: 10,
  },
  '리퀴드메탈 하트': {
    meta: {
      id: 1672077,
      version: 1,
    },
    name: '리퀴드메탈 하트',
    icon: '1672077',
    type: 167,
    req: {
      level: 120,
    },
    attributes: {
      trade: 2,
      canStarforce: 1,
      canScroll: 1,
      canPotential: 1,
      canAdditionalPotential: 1,
    },
    baseOption: {
      str: 3,
      dex: 3,
      int: 3,
      luk: 3,
      maxHp: 100,
    },
    scrollUpgradeableCount: 10,
  },
  '컴플리트 언더컨트롤': {
    meta: {
      id: 1672095,
      version: 1,
    },
    name: '컴플리트 언더컨트롤',
    icon: '1672095',
    type: 167,
    req: {
      level: 200,
    },
    attributes: {
      trade: 2,
      canStarforce: 1,
      canScroll: 1,
      canPotential: 1,
      canAdditionalPotential: 1,
    },
    baseOption: {
      str: 25,
      dex: 25,
      int: 25,
      luk: 25,
      maxHp: 1250,
      attackPower: 15,
      magicPower: 15,
      ignoreMonsterArmor: 30,
    },
    scrollUpgradeableCount: 10,
  },
  '쟈이힌 스태프': {
    meta: {
      id: 1382244,
      version: 1,
    },
    name: '쟈이힌 스태프',
    icon: '1382244',
    type: 138,
    req: {
      level: 130,
      job: 2,
    },
    attributes: {
      attackSpeed: 8,
      canStarforce: 1,
      canScroll: 1,
      canAddOption: 1,
      canPotential: 1,
      canAdditionalPotential: 1,
    },
    baseOption: {
      attackPower: 90,
      magicPower: 142,
    },
    scrollUpgradeableCount: 8,
  },
  '앱솔랩스 ESP리미터': {
    meta: {
      id: 1262017,
      version: 1,
    },
    name: '앱솔랩스 ESP리미터',
    icon: '1262017',
    type: 126,
    req: {
      level: 160,
      job: 2,
      class: 142,
    },
    attributes: {
      trade: 2,
      cuttable: 2,
      attackSpeed: 6,
      bossReward: true,
      incline: {
        charm: 100,
      },
      canStarforce: 1,
      canScroll: 1,
      canAddOption: 1,
      canPotential: 1,
      canAdditionalPotential: 1,
    },
    baseOption: {
      int: 60,
      luk: 60,
      attackPower: 143,
      magicPower: 241,
      bossDamage: 30,
      ignoreMonsterArmor: 10,
    },
    scrollUpgradeableCount: 9,
  },
  '아케인셰이드 샤이닝로드': {
    meta: {
      id: 1212120,
      version: 1,
    },
    name: '아케인셰이드 샤이닝로드',
    icon: '1212120',
    type: GearType.shiningRod,
    req: {
      level: 200,
      job: 2,
    },
    attributes: {
      trade: 2,
      cuttable: 2,
      bossReward: true,
      incline: {
        charm: 200,
      },
      canStarforce: 1,
      canScroll: 1,
      canAddOption: 1,
      canPotential: 1,
      canAdditionalPotential: 1,
    },
    baseOption: {
      int: 100,
      luk: 100,
      attackPower: 206,
      magicPower: 347,
      bossDamage: 30,
      ignoreMonsterArmor: 20,
    },
    scrollUpgradeableCount: 9,
  },
  '아케인셰이드 초선': {
    meta: {
      id: 1292018,
      version: 1,
    },
    name: '아케인셰이드 초선',
    icon: '1292018',
    type: 129,
    req: {
      level: 200,
      job: 8,
    },
    attributes: {
      trade: 2,
      cuttable: 2,
      attackSpeed: 4,
      bossReward: true,
      incline: {
        charm: 200,
      },
      canStarforce: 1,
      canScroll: 1,
      canAddOption: 1,
      canPotential: 1,
      canAdditionalPotential: 1,
    },
    baseOption: {
      dex: 100,
      luk: 100,
      attackPower: 276,
      bossDamage: 30,
      ignoreMonsterArmor: 20,
    },
    scrollUpgradeableCount: 9,
  },
  '레드 보우': {
    meta: {
      id: 1452220,
      version: 1,
    },
    name: '레드 보우',
    icon: '1452220',
    type: 145,
    req: {
      level: 75,
      job: 4,
    },
    attributes: {
      trade: 2,
      attackSpeed: 6,
      canStarforce: 1,
      canScroll: 1,
      canAddOption: 1,
      canPotential: 1,
      canAdditionalPotential: 1,
    },
    baseOption: {
      attackPower: 83,
    },
    scrollUpgradeableCount: 8,
  },
  '라즐리 9형': {
    meta: {
      id: 1572009,
      version: 1,
    },
    name: '라즐리 9형',
    icon: '1572009',
    type: 157,
    req: {
      level: 200,
      job: 1,
      class: 101,
    },
    attributes: {
      trade: 1,
      attackSpeed: 6,
      canStarforce: 1,
      canScroll: 1,
      canAddOption: 1,
      canPotential: 1,
      canAdditionalPotential: 1,
    },
    baseOption: {
      str: 100,
      dex: 100,
      attackPower: 293,
      bossDamage: 30,
      ignoreMonsterArmor: 20,
    },
    scrollUpgradeableCount: 9,
  },
  '제네시스 브레스 슈터': {
    meta: {
      id: 1214022,
      version: 1,
    },
    name: '제네시스 브레스 슈터',
    icon: '1214021',
    type: 1214,
    req: {
      level: 200,
      job: 4,
      class: 63,
    },
    attributes: {
      only: true,
      trade: 1,
      onlyEquip: true,
      attackSpeed: 4,
      lucky: true,
      bossReward: true,
      incline: {
        charm: 200,
      },
      canStarforce: 2,
      canScroll: 2,
      canAddOption: 1,
      canPotential: 1,
      canAdditionalPotential: 1,
    },
    baseOption: {
      str: 150,
      dex: 150,
      attackPower: 318,
      speed: 19,
      bossDamage: 30,
      ignoreMonsterArmor: 20,
    },
    scrollUpgradeableCount: 8,
  },
} satisfies Record<string, GearData>;
