import { AddOptionType, GearType } from '@malib/gear';
import { convert } from './convert';
import { ItemEquipmentInfo } from './data/ItemEquipment';

const sample: ItemEquipmentInfo = {
  item_equipment_part: '하의',
  item_equipment_slot: '하의',
  item_name: '에테르넬 메이지팬츠',
  item_icon: 'https://open.api.nexon.com/static/maplestory/item/icon/KEPEJFGH',
  item_description: null,
  item_shape_name: '에테르넬 메이지팬츠',
  item_shape_icon:
    'https://open.api.nexon.com/static/maplestory/item/icon/KEPEJFGH',
  item_gender: null,
  item_total_option: {
    str: '178',
    dex: '0',
    int: '376',
    luk: '256',
    max_hp: '255',
    max_mp: '0',
    attack_power: '120',
    magic_power: '172',
    armor: '1005',
    speed: '0',
    jump: '0',
    boss_damage: '0',
    ignore_monster_armor: '5',
    all_stat: '6',
    damage: '0',
    equipment_level_decrease: 0,
    max_hp_rate: '0',
    max_mp_rate: '0',
  },
  item_base_option: {
    str: '0',
    dex: '0',
    int: '50',
    luk: '50',
    max_hp: '0',
    max_mp: '0',
    attack_power: '0',
    magic_power: '6',
    armor: '325',
    speed: '0',
    jump: '0',
    boss_damage: '0',
    ignore_monster_armor: '5',
    all_stat: '0',
    max_hp_rate: '0',
    max_mp_rate: '0',
    base_equipment_level: 250,
  },
  potential_option_grade: '레전드리',
  additional_potential_option_grade: '레전드리',
  potential_option_flag: 'false',
  potential_option_1: 'INT +13%',
  potential_option_2: 'INT +13%',
  potential_option_3: '올스탯 +7%',
  additional_potential_option_flag: 'false',
  additional_potential_option_1: 'INT +9%',
  additional_potential_option_2: '마력 +15',
  additional_potential_option_3: 'INT +7%',
  equipment_level_increase: 0,
  item_exceptional_option: {
    str: '0',
    dex: '0',
    int: '0',
    luk: '0',
    max_hp: '0',
    max_mp: '0',
    attack_power: '0',
    magic_power: '0',
    exceptional_upgrade: 0,
  },
  item_add_option: {
    str: '42',
    dex: '0',
    int: '149',
    luk: '35',
    max_hp: '0',
    max_mp: '0',
    attack_power: '0',
    magic_power: '0',
    armor: '0',
    speed: '0',
    jump: '0',
    boss_damage: '0',
    damage: '0',
    all_stat: '6',
    equipment_level_decrease: 0,
  },
  growth_exp: 0,
  growth_level: 0,
  scroll_upgrade: '8',
  cuttable_count: '9',
  golden_hammer_flag: '미적용',
  scroll_resilience_count: '0',
  scroll_upgradeable_count: '0',
  soul_name: null,
  soul_option: null,
  item_etc_option: {
    str: '17',
    dex: '0',
    int: '18',
    luk: '12',
    max_hp: '0',
    max_mp: '0',
    attack_power: '0',
    magic_power: '46',
    armor: '13',
    speed: '0',
    jump: '0',
  },
  starforce: '22',
  starforce_scroll_flag: '미사용',
  item_starforce_option: {
    str: '119',
    dex: '0',
    int: '159',
    luk: '159',
    max_hp: '255',
    max_mp: '0',
    attack_power: '120',
    magic_power: '120',
    armor: '667',
    speed: '0',
    jump: '0',
  },
  special_ring_level: 0,
  date_expire: null,
  freestyle_flag: '0',
};

const expected = {
  version: 2,
  id: 1062286,
  name: '에테르넬 메이지팬츠',
  icon: '1062286',
  type: GearType.pants,
  addOption: {
    allStat: 6,
    int: 149,
    luk: 35,
    str: 42,
  },
  addOptions: [
    {
      grade: 6,
      type: AddOptionType.int,
      value: 72,
    },
    {
      grade: 6,
      type: AddOptionType.str_int,
      value: 42,
    },
    {
      grade: 5,
      type: AddOptionType.int_luk,
      value: 35,
    },
    {
      grade: 6,
      type: AddOptionType.allStat,
      value: 6,
    },
  ],
  additionalPotentialGrade: 4,
  additionalPotentials: [
    {
      grade: 4,
      id: 42043,
      option: {
        intRate: 9,
      },
      summary: 'INT +9%',
    },
    {
      grade: 3,
      id: 32012,
      option: {
        magicPower: 15,
      },
      summary: '마력 +15',
    },
    {
      grade: 3,
      id: 32043,
      option: {
        intRate: 7,
      },
      summary: 'INT +7%',
    },
  ],
  attributes: {},
  baseOption: {
    armor: 325,
    ignoreMonsterArmor: 5,
    int: 50,
    luk: 50,
    magicPower: 6,
  },
  potentialGrade: 4,
  potentials: [
    {
      grade: 4,
      id: 40043,
      option: {
        intRate: 13,
      },
      summary: 'INT +13%',
    },
    {
      grade: 4,
      id: 40043,
      option: {
        intRate: 13,
      },
      summary: 'INT +13%',
    },
    {
      grade: 3,
      id: 30086,
      option: {
        dexRate: 7,
        intRate: 7,
        lukRate: 7,
        strRate: 7,
      },
      summary: '올스탯 +7%',
    },
  ],
  req: {
    level: 250,
  },
  scrollUpgradeCount: 8,
  star: 22,
  starforceOption: {
    armor: 667,
    attackPower: 120,
    int: 159,
    luk: 159,
    magicPower: 120,
    maxHp: 255,
    str: 119,
  },
  upgradeOption: {
    allStat: 6,
    armor: 1005,
    attackPower: 120,
    ignoreMonsterArmor: 5,
    int: 376,
    luk: 256,
    magicPower: 172,
    maxHp: 255,
    str: 178,
  },
};

test('convert', () => {
  const gearData = convert(sample, '루미너스');
  expect(gearData).toEqual(expected);
});
