/**
 * 장비 속성
 */
enum GearPropType {
    incSTR = 1,
    incSTRr,
    incDEX,
    incDEXr,
    incINT,
    incINTr,
    incLUK,
    incLUKr,
    incAllStat_incMHP25,
    incAllStat,
    incMHP_incMMP,
    incMHPr_incMMPr,
    incMHP,
    incMMP,
    incMHPr,
    incMMPr,
    incMDF,
    incARC,
    incAUT,
    incPAD_incMAD,
    incPAD,
    incMAD,
    incAD,
    incPDD_incMDD,
    incPDD,
    // incMDD,
    // incACC_incEVA,
    // incACC,
    // incEVA,
    incSpeed,
    incJump,
    // incCraft,
    knockback,
    // incPVPDamage,
    bdR,
    incBDR,
    imdR,
    incIMDR,
    damR,
    nbdR,
    statR,
    incCHUC,
    bossReward,

    incPADr = 100,
    incMADr,
    incPDDr,
    incMDDr,
    incACCr,
    incEVAr,
    incCr,
    incDAMr,
    RecoveryHP,
    RecoveryMP,
    face,
    prop,
    time,
    HP,
    MP,
    attackType,
    ignoreTargetDEF,
    ignoreDAM,
    ignoreDAMr,
    DAMreflect,
    mpconReduce,
    mpRestore,
    incMesoProp,
    incRewardProp,
    incAllskill,
    RecoveryUP,
    boss,
    level,
    incTerR,
    incAsrR,
    incEXPr,
    reduceCooltime,
    incCriticaldamageMax,
    incCriticaldamageMin,
    incSTRlv,
    incDEXlv,
    incINTlv,
    incLUKlv,
    incMaxDamage,
    incMHPlv,
    incPADlv,
    incMADlv,
    incCriticaldamage,

    // Option,
    // OptionToMob,
    // activeSkill,
    // bonusByTime,

    attackSpeed = 200,
    tuc,
    setItemID,
    durability,
    // reqCraft,
    // cash,
    // royalSpecial,
    // masterSpecial,
    reduceReq,
    growthLevel,
    growthExp,

    mastery = 300,
    // criticaldamageMin,
    // criticaldamageMax,
    // criticaldamage,
    // epad,
    // emad,
    // epdd,
    // emdd,
    // emhp,
    // emmp,
    // smartpad,
    // smartacc,
    // smarteva,

    reqLevel = 1000,
    reqSTR,
    reqDEX,
    reqINT,
    reqLUK,
    reqJob,
    reqPOP,
    reqSpecJob,
    // reqWeekDay,
    // grade,

    only = 1100,
    // notSale,
    // dropBlock,
    tradeBlock,
    accountSharable,
    onlyEquip,
    tradeAvailable,
    equipTradeBlock,
    tradeOnce,
    sharableOnce,
    // notExtend,
    // epicItem,
    charismaEXP,
    senseEXP,
    insightEXP,
    willEXP,
    craftEXP,
    charmEXP,
    // cashForceCharmExp,
    accountShareTag,
    noPotential,
    fixedPotential,
    // timeLimited,
    specialGrade,
    fixedGrade,
    // unchangeable,
    superiorEqp,
    incPQEXPr,
    // limitBreak,
    // nActivatedSocket,
    jokerToSetItem,
    // medalTag,
    // ringOptionSkill,
    // ringOptionSkillLv,
    // abilityTimeLimited,
    blockGoldHammer,
    exceptUpgrade,
    // colorvar,
    // noMoveToLocker,
    onlyUpgrade,
    // cantRepair,
    // noPetEquipStatMoveItem,
    // BTSLabel,
    // android,
    tucIgnoreForPotential,

    yggdrasil = 2000,
    amazingScroll,
}

function asGearPropType(key: string): GearPropType {
    if(key in GearPropType) {
        return GearPropType[key as keyof typeof GearPropType];
    }
    throw Error(key + " key does not exist in GearPropType!");
}

export { GearPropType as default, asGearPropType };
