name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Cache turbo build setup
        uses: actions/cache@v4
        id: turbo-cache
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          cache: true

      - name: Install Dependencies
        run: pnpm install

      - name: Format check
        run: pnpm format:check

      - name: Lint check
        run: pnpm lint

      - name: Check types
        run: pnpm check

      - name: Test
        run: pnpm test
