name: CI
on:
  push:
    branches: [main, ci]
  pull_request:
    branches: [main, ci]
jobs:
  build:
    name: Build, lint and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['18']
        os: [ubuntu-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: master

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - run: pnpm exec nx workspace-lint
      - run: pnpm exec nx affected --target=lint --parallel=3
      - run: pnpm exec nx affected --target=test --parallel=3 --ci --code-coverage
      - run: pnpm exec nx affected --target=build --parallel=3

