name: CI
on:
  push:
    branches: [main, master, ci]
  pull_request:
    branches: [main, master, ci]
jobs:
  build:
    name: Test on Node ${{ matrix.node }} / ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['14', '16', '18']
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: master

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Lint nx files
        run: pnpm exec nx workspace-lint

      - name: Lint packages
        run: pnpm exec nx affected --target=lint --parallel=3

      - name: Test packages
        run: pnpm exec nx affected --target=test --parallel=3 --ci --code-coverage

      - name: Build packages
        run: pnpm exec nx affected --target=build --parallel=3
